version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only
      

    - package-ecosystem: "npm"
      directory: "/examples/todo-ps"
      schedule:
          interval: "daily"
      versioning-strategy: increase
      ignore:
          - dependency-name: "tailwindcss"
            versions:
                - "^4.0.0"

    - package-ecosystem: "npm"
      directory: "/examples/todo-vue"
      schedule:
          interval: "daily"
      versioning-strategy: increase
      ignore:
          - dependency-name: "tailwindcss"
            versions:
                - "^4.0.0"

    - package-ecosystem: "cargo"
      directory: "/examples/todo-yew/todomvc"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only
      

    - package-ecosystem: "cargo"
      directory: "/webview-sys"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only
      
